spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.24.108.245:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: uxtc-auth
          uri: lb://uxtc-auth
          predicates:
            - Path=/uxtc-auth/**
          filters:
            - StripPrefix=1
        - id: uxtc-user
          uri: lb://uxtc-user
          predicates:
            - Path=/uxtc-user/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://127.0.0.1:8411/uxtc-auth/rsa/publicKey' #配置RSA的公钥访问地址

  redis:
    host: 172.24.108.246 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1 #设置Sleuth的抽样收集概率

secure:
  ignore:
    urls: #配置白名单路径
      - "/swagger-ui.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/uxtc-auth/oauth/token"
      - "/uxtc-auth/rsa/publicKey"
      - "/uxtc-auth/getUserInfo/token"