spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uxtc_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234567890
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  #注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 172.24.108.245:8848

  redis:
    host: 172.24.108.246 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1 #设置Sleuth的抽样收集概率
    feign:
      enabled: true #启动链路追踪（默认为true）

seata:
  # 该属性需要与前面config.txt文件中的service.vgroupMapping后的值保持一致
  tx-service-group: my_test_tx_group
  config:
    nacos:
      namespace: 09117bf2-f71a-43c5-9a2a-9103882154e0
      serverAddr: 172.24.108.245:8848
      group: SEATA_GROUP # 这个值未生效, 在nacos中依然为DEFAULT_GROUP, 待检查原因
  registry:
    nacos:
      application: seata-server # seata 在nacos中的服务名
      serverAddr: 172.24.108.245:8848
      group: SEATA_GROUP # 分组需和seate分组一致
      namespace: 09117bf2-f71a-43c5-9a2a-9103882154e0

