server:
  port: 8401
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）

mybatis-plus:
  - config-location: classpath:mybatis/mybatis-config.xml
  - mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.springframework: info
    com.uxtc.cloud: debug