spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.24.108.245:8848

  datasource:
    url: jdbc:mysql://localhost:3306/uxtc_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234567890
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  redis:
    host: 172.24.108.246 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

  #进行链路追踪配置https://repo1.maven.org/maven2/io/zipkin/java/zipkin-server/进行jar包下载直接运行Java -jar  zipkin-jar包
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1 #设置Sleuth的抽样收集概率

#这是mybatis-plus的配置
mybatis-plus:
  - config-location: classpath:mybatis/mybatis-config.xml
  - mapper-locations: classpath:mapper/*.xml
#这个是mybatis的配置
#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml


