spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.24.108.245:8848
  datasource:
    url: jdbc:mysql://localhost:3306/uxtc_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234567890

  redis:
    host: 172.24.108.246 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

mybatis:
  mapper-locations:
    - classpath:dao/*.xml


